# type of database to use: postgresql or sqlite
database_type: postgresql
# host server
host: athras.fmi.fi
# database name (PostgreSQL)
database: cell_graph_test_table
# user name
user: ritvanen
# password
password: BorneArgon
# PROJ-compatible projection definition or coordinate system identifier (i.e.
# EPSG code) for the stored geometries, e.g.
# lon-lat: 4326
# Finnish map projection: 3067
# OPERA: +proj=laea +lat_0=55.0 +lon_0=10.0 +x_0=1950000.0 +y_0=-2100000.0 +units=m +ellps=WGS84
projection: "+proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +k_0=1 +x_0=2600000 +y_0=1200000 +ellps=bessel +towgs84=674.374,15.056,405.346,0,0,0,0 +units=m +no_defs"
